print('See you later, alligator!')
print('See you later, alligator!')
print('See you later, alligator!')
print('See you later, alligator!')
print('See you later, alligator!')
print('See you later, alligator!')
print('See you later, alligator!')
print('See you later, alligator!')
print('See you later, alligator!')
print('See you later, alligator!')
print('See you later, alligator!')
print('See you later, alligator!')
print('See you later, alligator!')
print('See you later, alligator!')
print('See you later, alligator!')
print('See you later, stupid gamer!')
KeyError
KeyboardInterrupt